//! Built-in tokenizers.

mod burmese;
mod camel_case;
mod char_group;
mod chinese_char;
mod classic;
mod code;
mod compound_word;
mod edge_ngram;
mod elision;
mod email;
mod emoji;
mod fingerprint;
mod hyphenated;
mod json_field;
mod keyword;
mod letter;
mod log;
mod lowercase;
mod markdown;
mod microblog;
mod ngram;
mod path_hierarchy;
mod pattern;
mod phone_number;
mod punctuation;
mod reverse;
mod script_boundary;
mod sentence;
mod simple_pattern;
mod sliding_window;
mod structured_id;
mod tab_separated;
mod thai;
mod truncate;
mod uax_url_email;
mod url;
mod wildcard;

pub use burmese::BurmeseTokenizer;
pub use camel_case::CamelCaseTokenizer;
pub use char_group::CharGroupTokenizer;
pub use chinese_char::ChineseCharTokenizer;
pub use classic::ClassicTokenizer;
pub use code::CodeTokenizer;
pub use compound_word::CompoundWordTokenizer;
pub use edge_ngram::EdgeNgramTokenizer;
pub use elision::ElisionTokenizer;
pub use email::EmailTokenizer;
pub use emoji::EmojiTokenizer;
pub use fingerprint::FingerprintTokenizer;
pub use hyphenated::HyphenatedTokenizer;
pub use json_field::JsonFieldTokenizer;
pub use keyword::KeywordTokenizer;
pub use letter::LetterTokenizer;
pub use log::LogTokenizer;
pub use lowercase::LowercaseTokenizer;
pub use markdown::MarkdownTokenizer;
pub use microblog::MicroBlogTokenizer;
pub use ngram::NgramTokenizer;
pub use path_hierarchy::PathHierarchyTokenizer;
pub use pattern::PatternTokenizer;
pub use phone_number::PhoneNumberTokenizer;
pub use punctuation::PunctuationTokenizer;
pub use reverse::ReverseTokenizer;
pub use script_boundary::ScriptBoundaryTokenizer;
pub use sentence::SentenceTokenizer;
pub use simple_pattern::SimplePatternSplitTokenizer;
pub use simple_pattern::SimplePatternTokenizer;
pub use sliding_window::SlidingWindowTokenizer;
pub use structured_id::StructuredIdTokenizer;
pub use tab_separated::TabSeparatedTokenizer;
pub use truncate::TruncateTokenizer;
pub use url::UrlTokenizer;
pub use wildcard::WildcardTokenizer;
// StandardTokenizer is provided by pizza-engine
pub use pizza_engine::analysis::StandardTokenizer;
pub use thai::ThaiTokenizer;
pub use uax_url_email::UaxUrlEmailTokenizer;
// WhitespaceTokenizer is provided by pizza-engine
pub use pizza_engine::analysis::WhitespaceTokenizer;
