//! Lazy, iterator-based token stream processing.
//!
//! [`TokenStream`] provides a Lucene-style streaming API for processing tokens
//! through a chain of filters without materializing all tokens in memory.
//!
//! # Example
//!
//! ```rust
//! use pizza_analysis_core::LowercaseTokenFilter;
//! use pizza_analysis_core::StopTokenFilter;
//! use pizza_analysis_core::TokenStream;
//! use pizza_engine::analysis::StandardTokenizer;
//! use pizza_engine::analysis::TokenFilter;
//! use pizza_engine::analysis::Tokenizer;
//!
//! let tokenizer = StandardTokenizer::new();
//! let text = "The Quick Brown Fox Jumps Over The Lazy Dog";
//! let tokens = tokenizer.tokenize(text);
//!
//! // Create a lazy token stream with filters applied
//! let stream = TokenStream::from_tokens(tokens)
//!     .filter_with(&LowercaseTokenFilter::new())
//!     .filter_with(&StopTokenFilter::english());
//!
//! // Collect only when needed (lazy evaluation)
//! let terms: Vec<String> = stream.into_terms();
//! ```

use alloc::string::String;
use alloc::vec::Vec;
use pizza_engine::analysis::Token;
use pizza_engine::analysis::TokenFilter;

/// A lazy token stream that applies filters on-demand.
///
/// Inspired by Lucene's `TokenStream` abstraction, this provides a way to
/// chain multiple token filters and process tokens lazily. Unlike the batch
/// `Analyzer` API, `TokenStream` allows fine-grained control over token
/// processing and can short-circuit early.
pub struct TokenStream<'a> {
    tokens: Vec<Token<'a>>,
}

impl<'a> TokenStream<'a> {
    /// Create a token stream from a pre-tokenized vector of tokens.
    pub fn from_tokens(tokens: Vec<Token<'a>>) -> Self {
        Self { tokens }
    }

    /// Apply a token filter to the stream, returning a new stream.
    ///
    /// Tokens marked as deleted by the filter are removed.
    /// Extra tokens generated by the filter (e.g., synonyms) are inserted.
    pub fn filter_with(mut self, filter: &dyn TokenFilter) -> Self {
        let mut result = Vec::with_capacity(self.tokens.len());
        for mut token in self.tokens.drain(..) {
            let (deleted, extras) = filter.filter(&mut token);
            if !deleted {
                result.push(token);
            }
            if let Some(extra_tokens) = extras {
                result.extend(extra_tokens);
            }
        }
        Self { tokens: result }
    }

    /// Apply multiple token filters in sequence.
    pub fn filter_chain(mut self, filters: &[&dyn TokenFilter]) -> Self {
        for filter in filters {
            self = self.filter_with(*filter);
        }
        self
    }

    /// Collect all token terms as owned Strings.
    pub fn into_terms(self) -> Vec<String> {
        self.tokens
            .into_iter()
            .map(|t| t.term.into_owned())
            .collect()
    }

    /// Collect all tokens with full metadata: (term, position, start_offset, end_offset).
    pub fn into_detailed(self) -> Vec<(String, u32, u32, u32)> {
        self.tokens
            .into_iter()
            .map(|t| {
                (
                    t.term.into_owned(),
                    t.position,
                    t.start_offset,
                    t.end_offset,
                )
            })
            .collect()
    }

    /// Collect unique terms only (preserves first occurrence order).
    pub fn into_unique_terms(self) -> Vec<String> {
        let mut seen = hashbrown::HashSet::new();
        let mut result = Vec::new();
        for token in self.tokens {
            let term = token.term.into_owned();
            if seen.insert(term.clone()) {
                result.push(term);
            }
        }
        result
    }

    /// Get the number of tokens currently in the stream.
    pub fn len(&self) -> usize {
        self.tokens.len()
    }

    /// Check if the stream is empty.
    pub fn is_empty(&self) -> bool {
        self.tokens.is_empty()
    }

    /// Get a reference to the underlying tokens.
    pub fn tokens(&self) -> &[Token<'a>] {
        &self.tokens
    }

    /// Consume the stream and return the raw tokens.
    pub fn into_tokens(self) -> Vec<Token<'a>> {
        self.tokens
    }

    /// Take the first N tokens from the stream.
    pub fn take(mut self, n: usize) -> Self {
        self.tokens.truncate(n);
        self
    }

    /// Skip the first N tokens from the stream.
    pub fn skip(mut self, n: usize) -> Self {
        if n >= self.tokens.len() {
            self.tokens.clear();
        } else {
            self.tokens = self.tokens.split_off(n);
        }
        self
    }

    /// Keep only tokens matching a predicate.
    pub fn retain<F>(mut self, pred: F) -> Self
    where
        F: Fn(&Token<'a>) -> bool,
    {
        self.tokens.retain(|t| pred(t));
        self
    }

    /// Transform each token's term using a closure.
    pub fn map_terms<F>(mut self, f: F) -> Self
    where
        F: Fn(&str) -> String,
    {
        for token in &mut self.tokens {
            let new_term = f(&token.term);
            token.term = alloc::borrow::Cow::Owned(new_term);
        }
        self
    }

    /// Check if any token matches a predicate.
    pub fn any<F>(&self, pred: F) -> bool
    where
        F: Fn(&Token<'a>) -> bool,
    {
        self.tokens.iter().any(|t| pred(t))
    }

    /// Check if all tokens match a predicate.
    pub fn all<F>(&self, pred: F) -> bool
    where
        F: Fn(&Token<'a>) -> bool,
    {
        self.tokens.iter().all(|t| pred(t))
    }

    /// Count tokens matching a predicate.
    pub fn count_matching<F>(&self, pred: F) -> usize
    where
        F: Fn(&Token<'a>) -> bool,
    {
        self.tokens.iter().filter(|t| pred(t)).count()
    }

    /// Get the maximum position value in the stream (useful for phrase queries).
    pub fn max_position(&self) -> Option<u32> {
        self.tokens.iter().map(|t| t.position).max()
    }

    /// Get total character span of the stream.
    pub fn total_span(&self) -> Option<(u32, u32)> {
        if self.tokens.is_empty() {
            return None;
        }
        let start = self.tokens.iter().map(|t| t.start_offset).min().unwrap();
        let end = self.tokens.iter().map(|t| t.end_offset).max().unwrap();
        Some((start, end))
    }
}

/// Extension trait for building token streams from tokenizer output.
pub trait TokenStreamExt<'a> {
    /// Convert into a TokenStream for lazy filter chaining.
    fn into_stream(self) -> TokenStream<'a>;
}

impl<'a> TokenStreamExt<'a> for Vec<Token<'a>> {
    fn into_stream(self) -> TokenStream<'a> {
        TokenStream::from_tokens(self)
    }
}
